spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    path: /h2-console
    settings:
      trace: false;
      web-allow-others: false


auth:
  secret: "miniprojectdemo"
  expirationTime: 99999999
  tokenPrefix: "Bearer "
  authorizationHeader: "Authorization"

#security:
#  oauth2:
#    resource:
#      filter-order: 3

